//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolShopP.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderProduct
    {
        public int ID { get; set; }
        public int Quantity { get; set; }
        public System.DateTime SaleDate { get; set; }
        public int IDP { get; set; }
        public string Title { get; set; }
        public string Name { get; set; }
        public byte[] PhotoProduct { get; set; }
        public string Email { get; set; }
    }
}
